### ISSUE TITLE
P2P needs a fix

### ISSUE THREAD

**Issue by WAZAAAAA0** [Yomalex/NetspherePiratesLauncher#1]
@Yomalex This is about the NetspherePirates emulator, excuse me for writing this here in this repo, but the issues are blocked on the main repo.

I see you have been fixing a lot of stuff lately, that's amazing.
But there's one thing that desperately needs fixing for S4 emus to succeed: the faulty netcode, there's too much lag with everyone playing on (R)(T).

Official has something like 90% "success rate" on P2P connections
On NetspherePirates it goes down to like 1% and falls back to the more laggy (R)(T) for 99% of the players
CC's "hacky" fix makes P2P work like 20% of the times

No one was able to really fix this yet, it could be anything like a simple typo or a copy&paste fail for what we know. If you have the time, I would recommend you to look into it, as it's arguably the single most important aspect of the game. Being connected with direct UDP P2P also automatically solves other heavily game-breaking bugs caused by server TCP (R)(T): invincible players and unreadable chat.

This is the little info I could gather about it:
https://github.com/wtfblub/NetspherePirates/issues/133
https://github.com/wtfblub/NetspherePirates/pull/200

**Comment by Yomalex** [comment]
i will take note of this issue, i'm testing now using Hamachi with a single tester and never get (R)(T)

**Comment by WAZAAAAA0** [comment]
Well, if YOU host the Hamachi server yourself for, let's say 6 players, then everyone should show as "P2P" only to you... because YOU ARE the server and people are directly connected to you. The other players would show as (R)(T) to each other instead. That's why it happens I believe.

Should you ever need to run some tests to fix the P2P, you can drop by the S4MAX Discord (pserver) to find some guinea pigs I guess. https://discord.gg/FMuaSqS

EDIT: little updates here https://github.com/wtfblub/NetspherePirates/pull/263
https://github.com/wtfblub/NetspherePirates/pull/264/

**Comment by enginelesscc** [comment]
okay, better dont care about p2p yet. 
All emulators(even private) have problems with udp.
I hope you can take a look at the udp header, i suspect it for not beeing complete and causing desync problems.

You can see the udp bug yourself if you deactivate/remove p2p(you have to be (R)(T)/relay'd) and try to talk in a room with more than 2 players using chat

Also, i cannot use the original ProudNet source to fix the header, becuase it has a different udp header and is not compatible with any ProudNet version of S4League.
A working fallback is a big dependency for proudnet.
Also, my pull requests to the normal repo show solutions for p2p, also one which will result in same p2p results like on official.

**Comment by WAZAAAAA0** [comment]
alright, after all this time TODAY P2P got fixed thanks to the contributions of based CC
FULL P2P ROOM:
![S4_20180401_220415_happyP2Pday.png](https://i.imgur.com/vRMmYa5.png)
this is not an april fools' prank fortunately LUL. Rejoice

**Comment by Yomalex** [comment]
Thx to @EngineLessCC
